# Generated by Django 5.2.9 on 2025-12-27 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension, VectorField
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Enable Extensions FIRST 🛡️
        VectorExtension(),
        UnaccentExtension(),
        TrigramExtension(),

        # 2. Then Create Models
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('vector', VectorField(dimensions=768)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, choices=[('project_info', 'Project Info'), ('team', 'Team'), ('budget', 'Budget & Finance'), ('tech', 'Tech Stack'), ('timeline', 'Timeline & Deadlines'), ('legal', 'Legal & Compliance'), ('other', 'Other')], default='other', max_length=50)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.project')),
            ],
        ),
    ]
