# Generated by Django 5.2.9 on 2025-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
