# Generated by Django 5.2.8 on 2025-12-31 17:26

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='raw_text',
            field=core.utils.EncryptedField(),
        ),
    ]
